# Documentation Organization Script
# Categorizes and moves markdown files to organized docs folder

$docMappings = @{
    # Getting Started
    '01-getting-started' = @(
        'README.md',
        'QUICK_START.md',
        'QUICK_START_SUPER_ADMIN.md',
        'QUICK_START_CAMERA_SCANNING.md',
        'QUICK_START_SCANNER.md',
        'INSTALLATION_STEPS.md',
        'PREREQUISITES_CHECK.md',
        'START_SERVERS.md',
        'RUN.md',
        'APP_FLOW_GUIDE.md'
    )
    
    # Architecture
    '02-architecture' = @(
        'COMPLETE_SYSTEM_OVERVIEW.md',
        'BACKEND_VS_FRONTEND_GAP_ANALYSIS.md',
        'AUTHENTICATION_FLOW_ANALYSIS.md',
        'IMPLEMENTATION_PLAN.md',
        'SCOPE_ANALYSIS.md',
        'POS_IMPLEMENTATION_STRATEGY.md',
        'FRONTEND_IMPLEMENTATION_ROADMAP.md',
        'IMPLEMENTATION_ROADMAP_CASHIER_ADMIN.md'
    )
    
    # Features
    '03-features' = @(
        'CASHIER_SYSTEM_COMPREHENSIVE_AUDIT.md',
        'CASHIER_ADMIN_ROLES_DEFINED.md',
        'CASHIER_ADMIN_ROLE_SEPARATION_ANALYSIS.md',
        'CASHIER_ROLE_BASED_ACCESS_CONTROL.md',
        'CASHIER_QUICK_ACTIONS_RESEARCH.md',
        'POS_UX_RESEARCH_AND_IMPROVEMENTS.md',
        'POS_UX_RESEARCH_COMPREHENSIVE.md',
        'POS_RESEARCH_EXECUTIVE_SUMMARY.md',
        'POS_SYSTEM_AUDIT_AND_RESEARCH.md',
        'CHECKOUT_UX_RESEARCH_IMPROVEMENTS.md',
        'CAMERA_SCANNING_MARKET_RESEARCH.md',
        'CAMERA_SCANNING_MVP_SUMMARY.md',
        'CAMERA_SCANNING_IMPLEMENTATION_GUIDE.md',
        'AUDIO_NOTIFICATION_RESEARCH.md',
        'AUDIO_IMPLEMENTATION_GUIDE.md',
        'SCANNER_BAR_VISUAL_GUIDE.md',
        'SCANNER_BAR_IMPLEMENTATION_PLAN.md',
        'BARCODE_SCANNING_ENHANCEMENT.md',
        'SHOP_VERIFICATION_SYSTEM_RESEARCH.md',
        'LOGIN_IMPROVEMENTS_RESEARCH_PLAN.md',
        'SMARTDUKA_VS_COMPETITORS.md',
        'STRATEGIC_POS_ENHANCEMENT_PLAN.md',
        'UI_UX_ENHANCEMENT_PLAN.md',
        'MOBILE_FIRST_OPTIMIZATION.md',
        'POS_OPTIMIZATION_RECOMMENDATION.md'
    )
    
    # Implementation
    '04-implementation' = @(
        'IMPLEMENTATION_COMPLETE.md',
        'IMPLEMENTATION_COMPLETE_NOV8.md',
        'IMPLEMENTATION_COMPLETE_SUMMARY.md',
        'IMPLEMENTATION_SUMMARY.md',
        'IMPLEMENTATION_SUMMARY_NOV8.md',
        'IMPLEMENTATION_SUMMARY_NOV_8.md',
        'IMPLEMENTATION_SUMMARY_PHASE_1_2_3.md',
        'IMPLEMENTATION_GUIDE_UI_UX.md',
        'COMPLETE_IMPLEMENTATION_SUMMARY.md',
        'CASHIER_MVP_IMPLEMENTATION_GUIDE.md',
        'CASHIER_PIN_COMPLETE_GUIDE.md',
        'CASHIER_PIN_BACKEND_IMPLEMENTATION.md',
        'CASHIER_PIN_FRONTEND_IMPLEMENTATION.md',
        'CASHIER_IMPLEMENTATION_PROGRESS.md',
        'CASHIER_INTEGRATION_CHECKLIST.md',
        'CHECKOUT_IMPROVEMENTS_IMPLEMENTATION.md',
        'CAMERA_FIRST_SCANNER_SETUP.md',
        'CAMERA_FIRST_QUICK_GUIDE.md',
        'SCANNER_BAR_IMPLEMENTATION_STARTED.md',
        'SCANNER_BAR_COMPLETE_IMPLEMENTATION.md',
        'SCANNER_BAR_OPTIMIZATION_COMPLETE.md',
        'SCANNER_BAR_IMPLEMENTATION_FINAL_SUMMARY.md',
        'BARCODE_SCANNER_ROBUST_FIX.md',
        'FINAL_SCANNER_SETUP.md',
        'SCANNER_FIX_COMPLETE.md',
        'SHOP_VERIFICATION_IMPLEMENTATION_PLAN.md',
        'SHOP_VERIFICATION_PHASE1_COMPLETE.md',
        'SHOP_VERIFICATION_PHASE2_PROGRESS.md',
        'SHOP_VERIFICATION_SYSTEM_COMPLETE_SUMMARY.md',
        'SHOP_VERIFICATION_SYSTEM_FINAL_COMPLETE.md',
        'LOGIN_IMPROVEMENTS_IMPLEMENTATION_COMPLETE.md',
        'EMAIL_CONSOLIDATION_COMPLETE.md',
        'FIELD_CONSOLIDATION_COMPLETE.md',
        'HUMAN_READABLE_SHOP_ID_IMPLEMENTATION.md',
        'AUTHENTICATION_IMPLEMENTATION_SUMMARY.md',
        'MULTI_TENANT_TRANSFORMATION_COMPLETE.md',
        'SUPER_ADMIN_LOGIN_IMPLEMENTATION_COMPLETE.md',
        'SUPER_ADMIN_SETUP_SCRIPTS_COMPLETE.md',
        'SUPER_ADMIN_SETUP_SUCCESS.md',
        'SUPER_ADMIN_SETUP_GUIDE.md',
        'ENHANCEMENTS_COMPLETE.md',
        'TRANSFORMATION_100_PERCENT_COMPLETE.md',
        'TRANSFORMATION_PROGRESS.md',
        'PARALLEL_IMPLEMENTATION_PROGRESS.md'
    )
    
    # Fixes and Troubleshooting
    '05-fixes-and-troubleshooting' = @(
        'ABORTERROR_FIX.md',
        'API_ERRORS_FIX.md',
        'API_URL_FIX.md',
        'ACTIVITY_LOGGING_FIX.md',
        'ACTIVITY_SCHEMA_FIX.md',
        'BARCODE_SCANNER_BUG_FIX.md',
        'BLACK_SCREEN_FIX.md',
        'BUG_FIX_VERIFICATION.md',
        'CAMERA_DIAGNOSTIC.md',
        'CAMERA_FEED_BLACK_SCREEN_FIX.md',
        'CAMERA_FEED_QUICK_FIX.md',
        'CAMERA_SCANNER_TROUBLESHOOTING.md',
        'CASHIER_401_UNAUTHORIZED_FIX.md',
        'CONSOLE_WARNING_RESOLVED.md',
        'CORS_CACHE_CONTROL_FIX.md',
        'CORS_FIX_GUIDE.md',
        'CORS_TROUBLESHOOTING.md',
        'DEEP_ANALYSIS_SCANNER_ISSUE.md',
        'DOM_CLEANUP_ERROR_FIX.md',
        'DOM_ERROR_ROOT_CAUSE_AND_FIX.md',
        'DUPLICATE_KEY_ERROR_FIX.md',
        'E11000_DUPLICATE_KEY_KRAPIN_FIX.md',
        'E11000_DUPLICATE_KEY_PHONE_FIX.md',
        'ERROR_FIXES_SUMMARY.md',
        'FIX_ASMJS_ERROR.md',
        'FIX_QUAGGA2_INSTALLATION.md',
        'FONT_PRELOAD_WARNING.md',
        'HEARTBEAT_ERROR_FIX.md',
        'HOME_PAGE_NAVIGATION_FIX.md',
        'KNOWN_ISSUES_FIXED.md',
        'KRAPIN_DUPLICATE_KEY_FIX.md',
        'KRAPIN_EMPTY_VALUE_FIX.md',
        'MONGOOSE_DUPLICATE_INDEX_FIX.md',
        'NAVBAR_FIX_SUMMARY.md',
        'REFERENCE_ERROR_FIXED.md',
        'ROUTE_ORDER_FIX.md',
        'SHOP_DETAILS_PAGE_FIX.md',
        'SSR_FIX_SUMMARY.md',
        'SUPER_ADMIN_401_FIX.md',
        'SUPER_ADMIN_COMPLETE_FIX.md',
        'SUPER_ADMIN_DASHBOARD_FIX.md',
        'SUPER_ADMIN_DEPENDENCY_FIX.md',
        'SUPER_ADMIN_LOGIN_DEBUG.md',
        'SUPER_ADMIN_LOGIN_FINAL_FIX.md',
        'SUPER_ADMIN_LOGIN_FIX.md',
        'SUPER_ADMIN_LOGIN_TROUBLESHOOTING.md',
        'TIMING_FIX_APPLIED.md',
        'TURBOPACK_HMR_FIX.md',
        'VERIFICATION_AUTO_ACTIVATION_FIX.md',
        'VERIFIED_SHOPS_VISIBILITY_FIX.md',
        'WORKSPACE_WARNING_FIXED.md',
        'NAVIGATION_FIXES_APPLIED.md',
        'ACCESSIBILITY_WARNINGS_FIXED.md'
    )
    
    # Phase Reports
    '06-phase-reports' = @(
        'PHASE_1_COMPLETE.md',
        'PHASE_1_IMPLEMENTATION_COMPLETE.md',
        'PHASE_1_MOBILE_FIRST_POS_IMPLEMENTATION.md',
        'PHASE_1_2_IMPLEMENTATION_COMPLETE.md',
        'PHASE_2_COMPLETE.md',
        'PHASE_2_COMPLETION_SUMMARY.md',
        'PHASE_2_IMPLEMENTATION_COMPLETE.md',
        'PHASE_2_IMPLEMENTATION_PLAN.md',
        'PHASE_2_IMPLEMENTATION_PROGRESS.md',
        'PHASE_2_POS_BEST_PRACTICES.md',
        'PHASE_2_RESEARCH_SUMMARY.md',
        'PHASE_2_TASK_CHECKLIST.md',
        'PHASE_2_TESTING_PLAN.md',
        'PHASE_2_EXECUTIVE_SUMMARY.md',
        'PHASE_2_EXECUTIVE_REPORT.md',
        'PHASE_2_FINAL_CHECKLIST.md',
        'PHASE_2_DEPLOYMENT_GUIDE.md',
        'PHASE_3_COMPLETE.md',
        'PHASE_3_COMPLETE_SUMMARY.md',
        'PHASE_3_IMPLEMENTATION_COMPLETE.md',
        'PHASE_3_IMPLEMENTATION_UPDATE.md',
        'PHASE_3_CRITICAL_FEATURES.md',
        'PHASE_3_FINAL_DELIVERY.md',
        'PHASE_3_FINAL_STATUS.md',
        'PHASE_3_OPTIMIZATION_GUIDE.md',
        'PHASE_3_PARALLEL_IMPLEMENTATION_STATUS.md',
        'PHASE_3_POS_ENHANCEMENTS_STARTED.md',
        'PHASE_3_API_DOCUMENTATION.md',
        'PHASE_4_COMPLETE.md',
        'PHASE_4_IMPLEMENTATION_COMPLETE.md',
        'PHASE_4_ADVANCED_FEATURES_PLAN.md',
        'PHASE_5_COMPLETE.md',
        'PHASE_5_IMPLEMENTATION_COMPLETE.md',
        'PHASE_6_COMPLETE.md',
        'PHASE_6_TESTING_CHECKLIST.md',
        'CHECKOUT_IMPROVEMENTS_ALL_PHASES_COMPLETE.md',
        'CHECKOUT_IMPROVEMENTS_PHASE1_COMPLETE.md',
        'CHECKOUT_IMPROVEMENTS_PHASE2_COMPLETE.md',
        'CHECKOUT_IMPROVEMENTS_PHASE3_COMPLETE.md',
        'CHECKOUT_IMPROVEMENTS_PHASE4_COMPLETE.md'
    )
    
    # Guides
    '07-guides' = @(
        'DEPLOYMENT_GUIDE.md',
        'TESTING_GUIDE.md',
        'NAVIGATION_GUIDE.md',
        'QUICK_REFERENCE_SUPER_ADMIN.md',
        'CASHIER_QUICK_REFERENCE.md',
        'SCANNER_BAR_QUICK_REFERENCE.md',
        'SUPER_ADMIN_ACCESS_GUIDE.md',
        'VERIFICATION_SYSTEM_QUICK_START.md',
        'SYSTEM_VERIFICATION_COMPLETE.md',
        'COMPLETE_TEST_PLAN.md',
        'PRE_LAUNCH_CHECKLIST.md',
        'QUICK_TASK_CHECKLIST.md',
        'MISSING_FEATURES_DETAILED_CHECKLIST.md',
        'MISSING_FRONTEND_COMPONENTS_TASKLIST.md',
        'SCANNER_BAR_TESTING_GUIDE.md',
        'MPESA_SETUP.md',
        'SIGNUP_REGISTRATION_FLOW.md',
        'VERIFICATION_FLOW_ANALYSIS.md',
        'VERIFICATION_LOBBY_IMPLEMENTATION.md',
        'ACCESSIBILITY_NAVIGATION_AUDIT.md',
        'BACKEND_CONNECTION_DIAGNOSTIC.md',
        'BACKEND_CONNECTION_TEST.md',
        'ACTION_ITEMS_NOV8.md',
        'QUICK_ACTIONS_HORIZONTAL_LAYOUT.md',
        'SCANNER_BAR_SIZE_OPTIMIZATION.md',
        'SCANNER_BAR_WIDTH_EXPANSION.md',
        'SCANNER_BAR_FINAL_DIMENSIONS.md',
        'SCANNER_BAR_FINAL_SPECS.md',
        'SCANNER_BAR_BEFORE_AFTER.md',
        'SCANNER_BAR_CAMERA_TOGGLE_QUICK_ACTIONS.md'
    )
    
    # Research
    '08-research' = @(
        'COMPREHENSIVE_AUDIT_REPORT.md',
        'COMPREHENSIVE_POS_AUDIT.md',
        'AUDIT_SUMMARY_AND_RECOMMENDATIONS.md',
        'EXECUTIVE_SUMMARY.md',
        'PROJECT_COMPLETION_SUMMARY.md',
        'PROGRESS_SUMMARY.md',
        'RESEARCH_SUMMARY_CASHIER_ADMIN.md',
        'CASHIER_PIN_LOGIN_AUDIT.md',
        'CASHIER_PIN_LOGIN_COMPLETE.md',
        'CASHIER_SYSTEM_SUMMARY.md',
        'CASHIER_DEPLOYMENT_READY.md',
        'CASHIER_QUICK_ACTIONS_RESEARCH.md',
        'CASHIER_ADMIN_ROLE_SEPARATION_ANALYSIS.md',
        'POS_PHASE_2_RESEARCH_AND_PLAN.md',
        'AUTHENTICATION_FLOW_ANALYSIS.md',
        'SHOP_VERIFICATION_BRAINSTORM_SUMMARY.md',
        'TOAST_POSITION_MIGRATION_RESEARCH.md',
        'README_STRATEGIC_PLAN.md',
        'SMART_DUKA_PROJECT_SCOPE.md',
        'CLEANUP_COMPLETE.md',
        'FINAL_IMPLEMENTATION_STATUS.md',
        'NAVBAR_SUPER_ADMIN_ISOLATION_COMPLETE.md',
        'SUPER_ADMIN_ISOLATION_VERIFIED.md',
        'SUPER_ADMIN_LOGIN_SUCCESS.md',
        'SUPER_ADMIN_LOGIN_REFINEMENTS.md',
        'SUPER_ADMIN_NAVBAR_COMPLETE_FIX.md',
        'SUPER_ADMIN_NAVBAR_ISOLATION_FIX.md',
        'SUPER_ADMIN_LOGIN_RESET_STEPS.md',
        'SUPER_ADMIN_LOGIN_FIX_STEPS.md',
        'SUPER_ADMIN_LOGIN_TEST.md',
        'VERIFIED_TO_ACTIVE_MIGRATION.md',
        'VERIFICATION_AUTO_ACTIVATION_FIX.md'
    )
}

# Move files to their categories
foreach ($category in $docMappings.Keys) {
    $categoryPath = "docs\$category"
    
    foreach ($file in $docMappings[$category]) {
        $sourcePath = $file
        $destPath = Join-Path $categoryPath $file
        
        if (Test-Path $sourcePath) {
            Move-Item -Path $sourcePath -Destination $destPath -Force
            Write-Host "Moved: $file -> $category"
        }
    }
}

Write-Host "`nDocumentation organization complete!"
Write-Host "All markdown files have been organized into the docs folder."
