// ============================================================================
// SmartDuka Business Type Profiles - Complete Configuration for Each Type
// ============================================================================

import {
  BusinessTypeId,
  BusinessTypeProfile,
  BusinessTypeFeatures,
  ProductFieldConfig,
  InventoryMode,
  POSMode,
  UnitOfMeasure,
} from './types';

// ---------------------------------------------------------------------------
// Shared defaults
// ---------------------------------------------------------------------------
const FEATURES_OFF: BusinessTypeFeatures = {
  expiryTracking: false,
  batchTracking: false,
  serialTracking: false,
  weightBasedSelling: false,
  ingredientManagement: false,
  variantSupport: false,
  modifierSupport: false,
  multiUnitPricing: false,
  tieredPricing: false,
  warrantyTracking: false,
  drugClassification: false,
  prescriptionTracking: false,
  vehicleCompatibility: false,
  coreChargeTracking: false,
  speciesApplicability: false,
  tableManagement: false,
  orderTypes: false,
  kitchenDisplay: false,
  billSplitting: false,
  tabManagement: false,
  tipsHandling: false,
  ageVerification: false,
  quickSellGrid: false,
  scaleIntegration: false,
  customerCredit: false,
  quotations: false,
  layaway: false,
  appointments: false,
  serviceTracking: false,
  productionTracking: false,
  wastageTracking: false,
  coldChainTracking: false,
};

const FIELDS_HIDDEN: ProductFieldConfig = {
  sku: 'visible',
  barcode: 'visible',
  brand: 'visible',
  cost: 'visible',
  expiryDate: 'hidden',
  batchNumber: 'hidden',
  lotNumber: 'hidden',
  weight: 'hidden',
  unitOfMeasure: 'hidden',
  serialNumber: 'hidden',
  warrantyMonths: 'hidden',
  imeiNumber: 'hidden',
  drugSchedule: 'hidden',
  dosageForm: 'hidden',
  strength: 'hidden',
  activeIngredient: 'hidden',
  requiresPrescription: 'hidden',
  storageConditions: 'hidden',
  ingredients: 'hidden',
  allergens: 'hidden',
  preparationTime: 'hidden',
  calorieCount: 'hidden',
  modifiers: 'hidden',
  size: 'hidden',
  color: 'hidden',
  material: 'hidden',
  season: 'hidden',
  vehicleMake: 'hidden',
  vehicleModel: 'hidden',
  vehicleYear: 'hidden',
  partNumber: 'hidden',
  oemNumber: 'hidden',
  coreCharge: 'hidden',
  dimensions: 'hidden',
  targetSpecies: 'hidden',
  withdrawalPeriod: 'hidden',
};

const DEFAULT_TAX = {
  enabled: true,
  rate: 0.16,
  name: 'VAT',
  description: 'Value Added Tax (16%)',
};

const DEFAULT_POS_CONFIG = {
  showBarcodeScanner: true,
  showWeightInput: false,
  showModifiers: false,
  showTableSelector: false,
  showOrderType: false,
  showQuickSellGrid: false,
  showSerialPrompt: false,
  showPrescriptionFields: false,
  receiptTitle: 'RECEIPT',
  defaultOrderType: 'standard' as const,
};

const DEFAULT_RECEIPT_CONFIG = {
  showExpiryDate: false,
  showBatchNumber: false,
  showSerialNumber: false,
  showWeight: false,
  showPrescriptionInfo: false,
  showTableNumber: false,
  showOrderType: false,
  footerMessage: 'Thank you for your purchase!',
};

// ---------------------------------------------------------------------------
// Business Type Profile Definitions
// ---------------------------------------------------------------------------

const GENERAL_STORE: BusinessTypeProfile = {
  id: BusinessTypeId.GENERAL_STORE,
  displayName: 'General Store / Duka',
  description: 'General retail store selling a variety of everyday goods',
  icon: 'Store',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.PACK, UnitOfMeasure.BOTTLE, UnitOfMeasure.KG],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    quickSellGrid: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Food & Beverages', children: [{ name: 'Snacks' }, { name: 'Drinks' }, { name: 'Cooking Oil' }, { name: 'Sugar & Salt' }, { name: 'Flour & Maize' }] },
    { name: 'Household', children: [{ name: 'Cleaning Products' }, { name: 'Toiletries' }, { name: 'Paper Products' }] },
    { name: 'Personal Care' },
    { name: 'Airtime & Scratch Cards' },
    { name: 'School Supplies' },
    { name: 'Other' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showQuickSellGrid: true },
  receiptConfig: DEFAULT_RECEIPT_CONFIG,
};

const SUPERMARKET: BusinessTypeProfile = {
  id: BusinessTypeId.SUPERMARKET,
  displayName: 'Supermarket',
  description: 'Full-service supermarket with departments and high product volume',
  icon: 'ShoppingCart',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT, InventoryMode.WEIGHT_BASED, InventoryMode.BATCH_TRACKED],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.GRAM, UnitOfMeasure.LITRE, UnitOfMeasure.PACK, UnitOfMeasure.BOTTLE, UnitOfMeasure.CARTON],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    batchTracking: true,
    weightBasedSelling: true,
    multiUnitPricing: true,
    tieredPricing: true,
    quickSellGrid: true,
    ageVerification: true,
    scaleIntegration: true,
    wastageTracking: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    batchNumber: 'visible',
    weight: 'visible',
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Fresh Produce', children: [{ name: 'Fruits' }, { name: 'Vegetables' }, { name: 'Herbs' }] },
    { name: 'Dairy & Eggs' },
    { name: 'Meat & Poultry' },
    { name: 'Bakery' },
    { name: 'Beverages', children: [{ name: 'Soft Drinks' }, { name: 'Juices' }, { name: 'Water' }, { name: 'Alcohol' }] },
    { name: 'Snacks & Confectionery' },
    { name: 'Canned & Packaged Foods' },
    { name: 'Cereals & Grains' },
    { name: 'Cooking Essentials', children: [{ name: 'Cooking Oil' }, { name: 'Spices' }, { name: 'Flour' }, { name: 'Sugar & Salt' }] },
    { name: 'Household & Cleaning' },
    { name: 'Personal Care & Hygiene' },
    { name: 'Baby Products' },
    { name: 'Frozen Foods' },
    { name: 'Pet Food' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showWeightInput: true, showQuickSellGrid: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showWeight: true },
};

const MINI_SUPERMARKET: BusinessTypeProfile = {
  id: BusinessTypeId.MINI_SUPERMARKET,
  displayName: 'Mini Supermarket',
  description: 'Smaller self-service store with a curated product range',
  icon: 'ShoppingBag',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT, InventoryMode.WEIGHT_BASED],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.PACK, UnitOfMeasure.BOTTLE],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    weightBasedSelling: true,
    multiUnitPricing: true,
    quickSellGrid: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    weight: 'visible',
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Food & Groceries' },
    { name: 'Beverages' },
    { name: 'Snacks' },
    { name: 'Household' },
    { name: 'Personal Care' },
    { name: 'Fresh Produce' },
    { name: 'Dairy' },
    { name: 'Frozen' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showWeightInput: true, showQuickSellGrid: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showWeight: true },
};

const WHOLESALE: BusinessTypeProfile = {
  id: BusinessTypeId.WHOLESALE,
  displayName: 'Wholesale Shop',
  description: 'Bulk selling to retailers and businesses with volume pricing',
  icon: 'Warehouse',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT, InventoryMode.BATCH_TRACKED],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.CARTON, UnitOfMeasure.BOX, UnitOfMeasure.CRATE, UnitOfMeasure.BAG, UnitOfMeasure.PACK, UnitOfMeasure.DOZEN, UnitOfMeasure.PIECE],
  defaultUnit: UnitOfMeasure.CARTON,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    batchTracking: true,
    multiUnitPricing: true,
    tieredPricing: true,
    customerCredit: true,
    quotations: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    batchNumber: 'visible',
    unitOfMeasure: 'required',
  },
  defaultCategories: [
    { name: 'Fast Moving Consumer Goods (FMCG)' },
    { name: 'Beverages' },
    { name: 'Household Products' },
    { name: 'Personal Care' },
    { name: 'Food & Snacks' },
    { name: 'Stationery' },
    { name: 'Electronics' },
    { name: 'Other' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Thank you for your business!' },
};

const PHARMACY: BusinessTypeProfile = {
  id: BusinessTypeId.PHARMACY,
  displayName: 'Pharmacy / Chemist',
  description: 'Pharmaceutical retail with prescription management and drug tracking',
  icon: 'Pill',
  category: 'health',
  inventoryModes: [InventoryMode.BATCH_TRACKED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.BATCH_TRACKED,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.TABLET, UnitOfMeasure.CAPSULE, UnitOfMeasure.BOTTLE, UnitOfMeasure.TUBE, UnitOfMeasure.SACHET, UnitOfMeasure.PACK, UnitOfMeasure.BOX],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    batchTracking: true,
    drugClassification: true,
    prescriptionTracking: true,
    multiUnitPricing: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'required',
    batchNumber: 'required',
    lotNumber: 'visible',
    unitOfMeasure: 'required',
    drugSchedule: 'required',
    dosageForm: 'required',
    strength: 'visible',
    activeIngredient: 'visible',
    requiresPrescription: 'required',
    storageConditions: 'visible',
  },
  defaultCategories: [
    { name: 'Prescription Drugs (POM)', description: 'Prescription-only medicines' },
    { name: 'Over the Counter (OTC)', children: [{ name: 'Pain Relief' }, { name: 'Cold & Flu' }, { name: 'Digestive Health' }, { name: 'Allergy Relief' }] },
    { name: 'Antibiotics' },
    { name: 'Chronic Medication', children: [{ name: 'Diabetes' }, { name: 'Hypertension' }, { name: 'Asthma' }, { name: 'HIV/ARV' }] },
    { name: 'Vitamins & Supplements' },
    { name: 'First Aid' },
    { name: 'Personal Care & Hygiene' },
    { name: 'Baby Care' },
    { name: 'Medical Devices', description: 'Thermometers, BP monitors, etc.' },
    { name: 'Herbal & Traditional' },
  ],
  defaultTaxConfig: { enabled: true, rate: 0, name: 'VAT', description: 'Medicines are VAT exempt' },
  posConfig: { ...DEFAULT_POS_CONFIG, showPrescriptionFields: true, receiptTitle: 'PHARMACY RECEIPT' },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showExpiryDate: true, showBatchNumber: true, showPrescriptionInfo: true, footerMessage: 'Follow dosage instructions. Consult your pharmacist.' },
};

const HARDWARE: BusinessTypeProfile = {
  id: BusinessTypeId.HARDWARE,
  displayName: 'Hardware Store',
  description: 'Building materials, tools, and construction supplies',
  icon: 'Hammer',
  category: 'specialty',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.BAG, UnitOfMeasure.METRE, UnitOfMeasure.FOOT, UnitOfMeasure.ROLL, UnitOfMeasure.SHEET, UnitOfMeasure.BOX, UnitOfMeasure.SET],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    multiUnitPricing: true,
    tieredPricing: true,
    customerCredit: true,
    quotations: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    unitOfMeasure: 'required',
    dimensions: 'visible',
  },
  defaultCategories: [
    { name: 'Building Materials', children: [{ name: 'Cement' }, { name: 'Iron Sheets' }, { name: 'Timber' }, { name: 'Nails & Screws' }, { name: 'Sand & Ballast' }] },
    { name: 'Plumbing', children: [{ name: 'Pipes' }, { name: 'Fittings' }, { name: 'Taps & Valves' }] },
    { name: 'Electrical', children: [{ name: 'Cables & Wires' }, { name: 'Switches & Sockets' }, { name: 'Bulbs & Lighting' }] },
    { name: 'Paint & Finishes' },
    { name: 'Tools', children: [{ name: 'Hand Tools' }, { name: 'Power Tools' }, { name: 'Measuring Tools' }] },
    { name: 'Doors & Windows' },
    { name: 'Roofing' },
    { name: 'Safety Equipment' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Thank you! Quality materials, fair prices.' },
};

const ELECTRONICS: BusinessTypeProfile = {
  id: BusinessTypeId.ELECTRONICS,
  displayName: 'Electronics Shop',
  description: 'Consumer electronics with serial number and warranty tracking',
  icon: 'Laptop',
  category: 'retail',
  inventoryModes: [InventoryMode.SERIALIZED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.SERIALIZED,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.SET, UnitOfMeasure.PAIR],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    serialTracking: true,
    warrantyTracking: true,
    customerCredit: true,
    layaway: true,
    serviceTracking: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    serialNumber: 'required',
    warrantyMonths: 'visible',
    imeiNumber: 'visible',
  },
  defaultCategories: [
    { name: 'TVs & Displays' },
    { name: 'Audio & Speakers' },
    { name: 'Computers & Laptops' },
    { name: 'Printers & Accessories' },
    { name: 'Home Appliances', children: [{ name: 'Kitchen Appliances' }, { name: 'Laundry' }, { name: 'Fans & Cooling' }] },
    { name: 'Cables & Adapters' },
    { name: 'Batteries & Power' },
    { name: 'Accessories' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showSerialPrompt: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showSerialNumber: true, footerMessage: 'Keep receipt for warranty claims.' },
};

const CLOTHING: BusinessTypeProfile = {
  id: BusinessTypeId.CLOTHING,
  displayName: 'Clothing & Apparel',
  description: 'Fashion retail with size, color, and seasonal variant support',
  icon: 'Shirt',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.PAIR, UnitOfMeasure.SET],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    variantSupport: true,
    layaway: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    size: 'required',
    color: 'required',
    material: 'visible',
    season: 'visible',
  },
  defaultCategories: [
    { name: 'Men\'s Wear', children: [{ name: 'Shirts' }, { name: 'Trousers' }, { name: 'Suits' }, { name: 'Casual Wear' }] },
    { name: 'Women\'s Wear', children: [{ name: 'Dresses' }, { name: 'Blouses' }, { name: 'Skirts' }, { name: 'Casual Wear' }] },
    { name: 'Children\'s Wear' },
    { name: 'Footwear', children: [{ name: 'Men\'s Shoes' }, { name: 'Women\'s Shoes' }, { name: 'Children\'s Shoes' }] },
    { name: 'Accessories', children: [{ name: 'Bags' }, { name: 'Belts' }, { name: 'Jewelry' }, { name: 'Watches' }] },
    { name: 'Undergarments' },
    { name: 'Sportswear' },
    { name: 'School Uniforms' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Thank you! Exchange within 7 days with receipt.' },
};

const GROCERY: BusinessTypeProfile = {
  id: BusinessTypeId.GROCERY,
  displayName: 'Grocery Store',
  description: 'Fresh produce and groceries with weight-based selling',
  icon: 'Apple',
  category: 'food_beverage',
  inventoryModes: [InventoryMode.UNIT_COUNT, InventoryMode.WEIGHT_BASED],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.KG, UnitOfMeasure.GRAM, UnitOfMeasure.PIECE, UnitOfMeasure.BUNCH, UnitOfMeasure.PACK, UnitOfMeasure.LITRE],
  defaultUnit: UnitOfMeasure.KG,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    weightBasedSelling: true,
    multiUnitPricing: true,
    quickSellGrid: true,
    scaleIntegration: true,
    wastageTracking: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    weight: 'visible',
    unitOfMeasure: 'required',
  },
  defaultCategories: [
    { name: 'Fruits' },
    { name: 'Vegetables' },
    { name: 'Cereals & Grains', children: [{ name: 'Rice' }, { name: 'Beans' }, { name: 'Maize' }, { name: 'Wheat' }] },
    { name: 'Cooking Essentials', children: [{ name: 'Cooking Oil' }, { name: 'Spices' }, { name: 'Salt & Sugar' }] },
    { name: 'Dairy & Eggs' },
    { name: 'Beverages' },
    { name: 'Canned & Packaged' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showWeightInput: true, showQuickSellGrid: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showWeight: true },
};

const BUTCHERY: BusinessTypeProfile = {
  id: BusinessTypeId.BUTCHERY,
  displayName: 'Butchery',
  description: 'Meat retail with weight-based pricing and cold chain tracking',
  icon: 'Beef',
  category: 'food_beverage',
  inventoryModes: [InventoryMode.WEIGHT_BASED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.WEIGHT_BASED,
  posMode: POSMode.WEIGH_SELL,
  defaultUnits: [UnitOfMeasure.KG, UnitOfMeasure.GRAM, UnitOfMeasure.PIECE],
  defaultUnit: UnitOfMeasure.KG,
  features: {
    ...FEATURES_OFF,
    weightBasedSelling: true,
    scaleIntegration: true,
    wastageTracking: true,
    coldChainTracking: true,
    quickSellGrid: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    weight: 'required',
    unitOfMeasure: 'required',
  },
  defaultCategories: [
    { name: 'Beef', children: [{ name: 'Steak Cuts' }, { name: 'Mince' }, { name: 'Ribs' }, { name: 'Offal' }] },
    { name: 'Chicken', children: [{ name: 'Whole Chicken' }, { name: 'Chicken Parts' }, { name: 'Chicken Mince' }] },
    { name: 'Goat / Mutton' },
    { name: 'Pork' },
    { name: 'Fish & Seafood' },
    { name: 'Sausages & Processed' },
    { name: 'Marinades & Spices' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showWeightInput: true, showQuickSellGrid: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showWeight: true, footerMessage: 'Fresh quality meat every day!' },
};

const BAKERY: BusinessTypeProfile = {
  id: BusinessTypeId.BAKERY,
  displayName: 'Bakery',
  description: 'Fresh baked goods with production tracking and perishable management',
  icon: 'CakeSlice',
  category: 'food_beverage',
  inventoryModes: [InventoryMode.UNIT_COUNT, InventoryMode.INGREDIENT_BASED],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.QUICK_SELL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.DOZEN, UnitOfMeasure.PACK],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    ingredientManagement: true,
    productionTracking: true,
    wastageTracking: true,
    quickSellGrid: true,
    modifierSupport: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    unitOfMeasure: 'visible',
    ingredients: 'visible',
    allergens: 'visible',
  },
  defaultCategories: [
    { name: 'Bread', children: [{ name: 'White Bread' }, { name: 'Brown Bread' }, { name: 'Specialty Bread' }] },
    { name: 'Cakes & Pastries', children: [{ name: 'Birthday Cakes' }, { name: 'Wedding Cakes' }, { name: 'Pastries' }, { name: 'Cupcakes' }] },
    { name: 'Buns & Rolls' },
    { name: 'Cookies & Biscuits' },
    { name: 'Pies & Samosas' },
    { name: 'Doughnuts & Mandazi' },
    { name: 'Custom Orders' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showQuickSellGrid: true, showModifiers: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Freshly baked with love!' },
};

const RESTAURANT: BusinessTypeProfile = {
  id: BusinessTypeId.RESTAURANT,
  displayName: 'Restaurant / Cafe',
  description: 'Food service with table management, modifiers, and kitchen integration',
  icon: 'UtensilsCrossed',
  category: 'food_beverage',
  inventoryModes: [InventoryMode.INGREDIENT_BASED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.INGREDIENT_BASED,
  posMode: POSMode.RESTAURANT,
  defaultUnits: [UnitOfMeasure.PLATE, UnitOfMeasure.PORTION, UnitOfMeasure.CUP, UnitOfMeasure.GLASS, UnitOfMeasure.PIECE, UnitOfMeasure.BOTTLE],
  defaultUnit: UnitOfMeasure.PLATE,
  features: {
    ...FEATURES_OFF,
    ingredientManagement: true,
    modifierSupport: true,
    tableManagement: true,
    orderTypes: true,
    kitchenDisplay: true,
    billSplitting: true,
    tabManagement: true,
    tipsHandling: true,
    wastageTracking: true,
    quickSellGrid: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    ingredients: 'visible',
    allergens: 'visible',
    preparationTime: 'visible',
    calorieCount: 'visible',
    modifiers: 'visible',
  },
  defaultCategories: [
    { name: 'Starters / Appetizers' },
    { name: 'Main Course', children: [{ name: 'Rice Dishes' }, { name: 'Ugali Dishes' }, { name: 'Chapati Dishes' }, { name: 'Pasta' }] },
    { name: 'Soups & Stews' },
    { name: 'Grills & BBQ' },
    { name: 'Sides' },
    { name: 'Beverages', children: [{ name: 'Hot Drinks' }, { name: 'Cold Drinks' }, { name: 'Juices' }, { name: 'Alcohol' }] },
    { name: 'Desserts' },
    { name: 'Breakfast' },
    { name: 'Specials / Chef\'s Choice' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: {
    ...DEFAULT_POS_CONFIG,
    showModifiers: true,
    showTableSelector: true,
    showOrderType: true,
    showQuickSellGrid: true,
    receiptTitle: 'ORDER',
    defaultOrderType: 'dine_in',
  },
  receiptConfig: {
    ...DEFAULT_RECEIPT_CONFIG,
    showTableNumber: true,
    showOrderType: true,
    footerMessage: 'Thank you for dining with us!',
  },
};

const STATIONERY: BusinessTypeProfile = {
  id: BusinessTypeId.STATIONERY,
  displayName: 'Stationery Shop',
  description: 'Office and school supplies with seasonal demand management',
  icon: 'PenTool',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.PACK, UnitOfMeasure.REAM, UnitOfMeasure.BOX, UnitOfMeasure.SET, UnitOfMeasure.DOZEN],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    multiUnitPricing: true,
    tieredPricing: true,
    customerCredit: true,
    quotations: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Writing Instruments', children: [{ name: 'Pens' }, { name: 'Pencils' }, { name: 'Markers' }] },
    { name: 'Paper & Notebooks', children: [{ name: 'Exercise Books' }, { name: 'Notebooks' }, { name: 'Printing Paper' }, { name: 'Ruled Paper' }] },
    { name: 'Files & Folders' },
    { name: 'Art Supplies' },
    { name: 'Office Supplies', children: [{ name: 'Staplers & Pins' }, { name: 'Tape & Glue' }, { name: 'Scissors' }] },
    { name: 'School Bags' },
    { name: 'Printing & Photocopying' },
    { name: 'Gift Wrap & Cards' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: DEFAULT_RECEIPT_CONFIG,
};

const MOBILE_PHONE: BusinessTypeProfile = {
  id: BusinessTypeId.MOBILE_PHONE,
  displayName: 'Mobile Phone Shop',
  description: 'Phone retail with IMEI tracking, warranty, and repair services',
  icon: 'Smartphone',
  category: 'retail',
  inventoryModes: [InventoryMode.SERIALIZED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.SERIALIZED,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.SET],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    serialTracking: true,
    warrantyTracking: true,
    layaway: true,
    serviceTracking: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    serialNumber: 'visible',
    imeiNumber: 'required',
    warrantyMonths: 'visible',
  },
  defaultCategories: [
    { name: 'Smartphones', children: [{ name: 'Samsung' }, { name: 'iPhone' }, { name: 'Tecno' }, { name: 'Infinix' }, { name: 'Nokia' }, { name: 'Other Brands' }] },
    { name: 'Feature Phones' },
    { name: 'Tablets' },
    { name: 'Accessories', children: [{ name: 'Cases & Covers' }, { name: 'Chargers' }, { name: 'Earphones & Headphones' }, { name: 'Screen Protectors' }, { name: 'Power Banks' }] },
    { name: 'Airtime & Data' },
    { name: 'Sim Cards' },
    { name: 'Repair Services' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showSerialPrompt: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showSerialNumber: true, footerMessage: 'Keep receipt for warranty. IMEI recorded.' },
};

const BEAUTY_COSMETICS: BusinessTypeProfile = {
  id: BusinessTypeId.BEAUTY_COSMETICS,
  displayName: 'Beauty & Cosmetics',
  description: 'Beauty products with shade/variant tracking and expiry management',
  icon: 'Sparkles',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.BOTTLE, UnitOfMeasure.TUBE, UnitOfMeasure.SET, UnitOfMeasure.PACK],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    variantSupport: true,
    batchTracking: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    batchNumber: 'visible',
    color: 'visible',
    size: 'visible',
  },
  defaultCategories: [
    { name: 'Skincare', children: [{ name: 'Moisturizers' }, { name: 'Serums' }, { name: 'Sunscreen' }] },
    { name: 'Makeup', children: [{ name: 'Foundation' }, { name: 'Lipstick' }, { name: 'Eye Makeup' }, { name: 'Nail Polish' }] },
    { name: 'Hair Care', children: [{ name: 'Shampoo' }, { name: 'Conditioner' }, { name: 'Hair Treatment' }, { name: 'Wigs & Extensions' }] },
    { name: 'Fragrances' },
    { name: 'Body Care' },
    { name: 'Men\'s Grooming' },
    { name: 'Tools & Brushes' },
    { name: 'Natural & Organic' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showExpiryDate: true },
};

const AUTO_PARTS: BusinessTypeProfile = {
  id: BusinessTypeId.AUTO_PARTS,
  displayName: 'Auto Parts Shop',
  description: 'Vehicle parts with compatibility tracking and core charges',
  icon: 'Car',
  category: 'specialty',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.SET, UnitOfMeasure.PAIR, UnitOfMeasure.LITRE, UnitOfMeasure.PACK],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    vehicleCompatibility: true,
    coreChargeTracking: true,
    customerCredit: true,
    quotations: true,
    warrantyTracking: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    vehicleMake: 'visible',
    vehicleModel: 'visible',
    vehicleYear: 'visible',
    partNumber: 'required',
    oemNumber: 'visible',
    coreCharge: 'visible',
    warrantyMonths: 'visible',
  },
  defaultCategories: [
    { name: 'Engine Parts', children: [{ name: 'Filters' }, { name: 'Belts' }, { name: 'Gaskets' }, { name: 'Spark Plugs' }] },
    { name: 'Brake System' },
    { name: 'Suspension & Steering' },
    { name: 'Electrical', children: [{ name: 'Batteries' }, { name: 'Alternators' }, { name: 'Starters' }, { name: 'Bulbs' }] },
    { name: 'Body Parts' },
    { name: 'Oils & Fluids', children: [{ name: 'Engine Oil' }, { name: 'Brake Fluid' }, { name: 'Coolant' }, { name: 'Transmission Fluid' }] },
    { name: 'Tyres & Wheels' },
    { name: 'Accessories' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Parts warranty applies. Keep receipt.' },
};

const AGRO_VET: BusinessTypeProfile = {
  id: BusinessTypeId.AGRO_VET,
  displayName: 'Agro-Vet Shop',
  description: 'Agricultural and veterinary supplies with batch tracking and species info',
  icon: 'Sprout',
  category: 'specialty',
  inventoryModes: [InventoryMode.BATCH_TRACKED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.BATCH_TRACKED,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.LITRE, UnitOfMeasure.ML, UnitOfMeasure.PACK, UnitOfMeasure.BAG, UnitOfMeasure.BOTTLE, UnitOfMeasure.SACHET],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    batchTracking: true,
    speciesApplicability: true,
    multiUnitPricing: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'required',
    batchNumber: 'required',
    lotNumber: 'visible',
    unitOfMeasure: 'required',
    targetSpecies: 'visible',
    withdrawalPeriod: 'visible',
  },
  defaultCategories: [
    { name: 'Animal Health', children: [{ name: 'Dewormers' }, { name: 'Antibiotics' }, { name: 'Vaccines' }, { name: 'Supplements' }] },
    { name: 'Animal Feeds', children: [{ name: 'Dairy Feeds' }, { name: 'Poultry Feeds' }, { name: 'Pig Feeds' }, { name: 'Pet Food' }] },
    { name: 'Crop Protection', children: [{ name: 'Pesticides' }, { name: 'Herbicides' }, { name: 'Fungicides' }] },
    { name: 'Seeds & Seedlings' },
    { name: 'Fertilizers' },
    { name: 'Farm Equipment' },
    { name: 'Dairy Equipment' },
    { name: 'Poultry Equipment' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, showExpiryDate: true, showBatchNumber: true, footerMessage: 'Follow usage instructions. Observe withdrawal periods.' },
};

const FURNITURE: BusinessTypeProfile = {
  id: BusinessTypeId.FURNITURE,
  displayName: 'Furniture Store',
  description: 'Furniture retail with dimensions, custom orders, and layaway',
  icon: 'Sofa',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.SET],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    variantSupport: true,
    customerCredit: true,
    layaway: true,
    quotations: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    dimensions: 'visible',
    color: 'visible',
    material: 'visible',
  },
  defaultCategories: [
    { name: 'Living Room', children: [{ name: 'Sofas' }, { name: 'Coffee Tables' }, { name: 'TV Stands' }] },
    { name: 'Bedroom', children: [{ name: 'Beds' }, { name: 'Wardrobes' }, { name: 'Dressers' }, { name: 'Mattresses' }] },
    { name: 'Dining' },
    { name: 'Office Furniture' },
    { name: 'Outdoor' },
    { name: 'Storage' },
    { name: 'Custom Orders' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Delivery available. Ask about our layaway plan!' },
};

const LIQUOR: BusinessTypeProfile = {
  id: BusinessTypeId.LIQUOR,
  displayName: 'Liquor Store / Wine & Spirits',
  description: 'Alcohol retail with age verification and regulatory compliance',
  icon: 'Wine',
  category: 'food_beverage',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.BOTTLE, UnitOfMeasure.PACK, UnitOfMeasure.CRATE, UnitOfMeasure.GLASS, UnitOfMeasure.PIECE],
  defaultUnit: UnitOfMeasure.BOTTLE,
  features: {
    ...FEATURES_OFF,
    ageVerification: true,
    batchTracking: true,
    quickSellGrid: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    batchNumber: 'visible',
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Beer', children: [{ name: 'Local Beer' }, { name: 'Imported Beer' }, { name: 'Craft Beer' }] },
    { name: 'Wine', children: [{ name: 'Red Wine' }, { name: 'White Wine' }, { name: 'Sparkling' }] },
    { name: 'Spirits', children: [{ name: 'Whisky' }, { name: 'Vodka' }, { name: 'Brandy' }, { name: 'Gin' }, { name: 'Rum' }] },
    { name: 'Ready-to-Drink (RTD)' },
    { name: 'Mixers & Non-Alcoholic' },
    { name: 'Cigarettes & Tobacco' },
    { name: 'Snacks' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showQuickSellGrid: true },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Drink responsibly. 18+ only.' },
};

const BOOKSHOP: BusinessTypeProfile = {
  id: BusinessTypeId.BOOKSHOP,
  displayName: 'Bookshop',
  description: 'Books and educational materials',
  icon: 'BookOpen',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.SET, UnitOfMeasure.PACK],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    tieredPricing: true,
    customerCredit: true,
    quotations: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
  },
  defaultCategories: [
    { name: 'Textbooks', children: [{ name: 'Primary School' }, { name: 'Secondary School' }, { name: 'University' }] },
    { name: 'Fiction' },
    { name: 'Non-Fiction' },
    { name: 'Children\'s Books' },
    { name: 'Reference' },
    { name: 'Religious' },
    { name: 'Stationery' },
  ],
  defaultTaxConfig: { enabled: true, rate: 0, name: 'VAT', description: 'Books are VAT exempt' },
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: DEFAULT_RECEIPT_CONFIG,
};

const GIFT_SHOP: BusinessTypeProfile = {
  id: BusinessTypeId.GIFT_SHOP,
  displayName: 'Gift Shop',
  description: 'Gift items, souvenirs, and novelty products',
  icon: 'Gift',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.SET],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    variantSupport: true,
    layaway: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    size: 'visible',
    color: 'visible',
  },
  defaultCategories: [
    { name: 'Home Decor' },
    { name: 'Greeting Cards' },
    { name: 'Flowers & Plants' },
    { name: 'Gift Hampers' },
    { name: 'Jewelry & Accessories' },
    { name: 'Toys & Games' },
    { name: 'Souvenirs' },
    { name: 'Gift Vouchers' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Gift wrapping available!' },
};

const PET_SHOP: BusinessTypeProfile = {
  id: BusinessTypeId.PET_SHOP,
  displayName: 'Pet Shop',
  description: 'Pet supplies, food, and accessories',
  icon: 'PawPrint',
  category: 'specialty',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.PACK, UnitOfMeasure.BAG, UnitOfMeasure.BOTTLE],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    expiryTracking: true,
    speciesApplicability: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    expiryDate: 'visible',
    targetSpecies: 'visible',
  },
  defaultCategories: [
    { name: 'Dog Supplies', children: [{ name: 'Dog Food' }, { name: 'Dog Treats' }, { name: 'Dog Accessories' }] },
    { name: 'Cat Supplies', children: [{ name: 'Cat Food' }, { name: 'Cat Litter' }, { name: 'Cat Accessories' }] },
    { name: 'Fish & Aquarium' },
    { name: 'Bird Supplies' },
    { name: 'Small Pets' },
    { name: 'Pet Health' },
    { name: 'Pet Grooming' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: DEFAULT_RECEIPT_CONFIG,
};

const SALON_BARBERSHOP: BusinessTypeProfile = {
  id: BusinessTypeId.SALON_BARBERSHOP,
  displayName: 'Salon / Barbershop',
  description: 'Service-based business with appointments and product sales',
  icon: 'Scissors',
  category: 'service',
  inventoryModes: [InventoryMode.SERVICE_BASED, InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.SERVICE_BASED,
  posMode: POSMode.SERVICE,
  defaultUnits: [UnitOfMeasure.SERVICE, UnitOfMeasure.SESSION, UnitOfMeasure.PIECE],
  defaultUnit: UnitOfMeasure.SERVICE,
  features: {
    ...FEATURES_OFF,
    appointments: true,
    serviceTracking: true,
    tipsHandling: true,
    modifierSupport: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Haircuts', children: [{ name: 'Men\'s Haircut' }, { name: 'Women\'s Haircut' }, { name: 'Children\'s Haircut' }] },
    { name: 'Hair Styling' },
    { name: 'Hair Treatment', children: [{ name: 'Relaxer' }, { name: 'Keratin' }, { name: 'Deep Conditioning' }] },
    { name: 'Hair Coloring' },
    { name: 'Braiding & Weaving' },
    { name: 'Nail Services' },
    { name: 'Facial & Skincare' },
    { name: 'Shaving & Grooming' },
    { name: 'Products for Sale' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: {
    ...DEFAULT_POS_CONFIG,
    showBarcodeScanner: false,
    showQuickSellGrid: true,
    receiptTitle: 'SERVICE RECEIPT',
  },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Thank you! See you next time.' },
};

const LAUNDRY: BusinessTypeProfile = {
  id: BusinessTypeId.LAUNDRY,
  displayName: 'Laundry / Dry Cleaning',
  description: 'Laundry and dry cleaning service tracking',
  icon: 'WashingMachine',
  category: 'service',
  inventoryModes: [InventoryMode.SERVICE_BASED],
  defaultInventoryMode: InventoryMode.SERVICE_BASED,
  posMode: POSMode.SERVICE,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.KG, UnitOfMeasure.SERVICE],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    serviceTracking: true,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    unitOfMeasure: 'visible',
  },
  defaultCategories: [
    { name: 'Washing', children: [{ name: 'Regular Wash' }, { name: 'Delicate Wash' }, { name: 'Heavy Duty' }] },
    { name: 'Dry Cleaning' },
    { name: 'Ironing / Pressing' },
    { name: 'Stain Removal' },
    { name: 'Alterations' },
    { name: 'Shoe Cleaning' },
    { name: 'Carpet & Rug Cleaning' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: {
    ...DEFAULT_POS_CONFIG,
    showBarcodeScanner: false,
    showQuickSellGrid: true,
    receiptTitle: 'SERVICE RECEIPT',
  },
  receiptConfig: { ...DEFAULT_RECEIPT_CONFIG, footerMessage: 'Pickup in 24-48 hours. Keep this receipt.' },
};

const GAS_STATION: BusinessTypeProfile = {
  id: BusinessTypeId.GAS_STATION,
  displayName: 'Gas / Petrol Station',
  description: 'Fuel retail with volume-based selling and convenience store',
  icon: 'Fuel',
  category: 'specialty',
  inventoryModes: [InventoryMode.UNIT_COUNT, InventoryMode.WEIGHT_BASED],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.QUICK_SELL,
  defaultUnits: [UnitOfMeasure.LITRE, UnitOfMeasure.KG, UnitOfMeasure.PIECE, UnitOfMeasure.BOTTLE],
  defaultUnit: UnitOfMeasure.LITRE,
  features: {
    ...FEATURES_OFF,
    weightBasedSelling: true,
    quickSellGrid: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    unitOfMeasure: 'required',
  },
  defaultCategories: [
    { name: 'Fuel', children: [{ name: 'Petrol / Super' }, { name: 'Diesel' }, { name: 'Kerosene' }] },
    { name: 'Lubricants', children: [{ name: 'Engine Oil' }, { name: 'Gear Oil' }, { name: 'Grease' }] },
    { name: 'LPG Gas' },
    { name: 'Convenience Store' },
    { name: 'Car Wash' },
    { name: 'Tyre Services' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: { ...DEFAULT_POS_CONFIG, showQuickSellGrid: true },
  receiptConfig: DEFAULT_RECEIPT_CONFIG,
};

const OTHER: BusinessTypeProfile = {
  id: BusinessTypeId.OTHER,
  displayName: 'Other',
  description: 'Custom business type with basic retail features',
  icon: 'Building',
  category: 'retail',
  inventoryModes: [InventoryMode.UNIT_COUNT],
  defaultInventoryMode: InventoryMode.UNIT_COUNT,
  posMode: POSMode.RETAIL,
  defaultUnits: [UnitOfMeasure.PIECE, UnitOfMeasure.PACK, UnitOfMeasure.KG, UnitOfMeasure.LITRE, UnitOfMeasure.SERVICE],
  defaultUnit: UnitOfMeasure.PIECE,
  features: {
    ...FEATURES_OFF,
    customerCredit: true,
  },
  productFields: {
    ...FIELDS_HIDDEN,
    unitOfMeasure: 'visible',
    expiryDate: 'visible',
  },
  defaultCategories: [
    { name: 'Category 1' },
    { name: 'Category 2' },
    { name: 'Category 3' },
    { name: 'Other' },
  ],
  defaultTaxConfig: DEFAULT_TAX,
  posConfig: DEFAULT_POS_CONFIG,
  receiptConfig: DEFAULT_RECEIPT_CONFIG,
};

// ---------------------------------------------------------------------------
// Profile Registry
// ---------------------------------------------------------------------------
export const BUSINESS_TYPE_PROFILES: Record<BusinessTypeId, BusinessTypeProfile> = {
  [BusinessTypeId.GENERAL_STORE]: GENERAL_STORE,
  [BusinessTypeId.SUPERMARKET]: SUPERMARKET,
  [BusinessTypeId.MINI_SUPERMARKET]: MINI_SUPERMARKET,
  [BusinessTypeId.WHOLESALE]: WHOLESALE,
  [BusinessTypeId.PHARMACY]: PHARMACY,
  [BusinessTypeId.HARDWARE]: HARDWARE,
  [BusinessTypeId.ELECTRONICS]: ELECTRONICS,
  [BusinessTypeId.CLOTHING]: CLOTHING,
  [BusinessTypeId.GROCERY]: GROCERY,
  [BusinessTypeId.BUTCHERY]: BUTCHERY,
  [BusinessTypeId.BAKERY]: BAKERY,
  [BusinessTypeId.RESTAURANT]: RESTAURANT,
  [BusinessTypeId.STATIONERY]: STATIONERY,
  [BusinessTypeId.MOBILE_PHONE]: MOBILE_PHONE,
  [BusinessTypeId.BEAUTY_COSMETICS]: BEAUTY_COSMETICS,
  [BusinessTypeId.AUTO_PARTS]: AUTO_PARTS,
  [BusinessTypeId.AGRO_VET]: AGRO_VET,
  [BusinessTypeId.FURNITURE]: FURNITURE,
  [BusinessTypeId.LIQUOR]: LIQUOR,
  [BusinessTypeId.BOOKSHOP]: BOOKSHOP,
  [BusinessTypeId.GIFT_SHOP]: GIFT_SHOP,
  [BusinessTypeId.PET_SHOP]: PET_SHOP,
  [BusinessTypeId.SALON_BARBERSHOP]: SALON_BARBERSHOP,
  [BusinessTypeId.LAUNDRY]: LAUNDRY,
  [BusinessTypeId.GAS_STATION]: GAS_STATION,
  [BusinessTypeId.OTHER]: OTHER,
};
